apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-app
  template:
    metadata:
      labels:
        app: order-app
    spec:
      containers:
      - name: order-app
        image: LOCATION-docker.pkg.dev/PROJECT_ID/REPOSITORY/IMAGE:TAG
        resources:
          requests:
            memory: "64Mi"
            cpu: "30m"
          limits:
            memory: "64Mi"
            cpu: "30m"
        ports:
        - containerPort: 3004
          protocol: TCP
        env:
        # - name: GRPC_XDS_BOOTSTRAP
        #   value: /bootstrap.json
        - name: ORDER_DB_NAME
          valueFrom:
            secretKeyRef:
              name: order-secret
              key: name
        - name: ORDER_DB_USER
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: user
        - name: ORDER_DB_PWD
          valueFrom:
            secretKeyRef:
              name: user-secret
              key: pwd
        - name: PP_CLTID
          valueFrom:
            secretKeyRef:
              name: order-secret
              key: pp_cltid
        - name: PP_SECRET
          valueFrom:
            secretKeyRef:
              name: order-secret
              key: pp_secret
        - name: PP_API
          valueFrom:
            secretKeyRef:
              name: order-secret
              key: pp_api
        - name: FRONT_HOST
          value: http://34.160.186.92
        - name: ORDER_DB_HOST
          value: localhost
        - name: ORDER_DB_PORT
          value: '5432'
        - name: APP_NAME
          value: Punto y Coma
        - name: ORDER_HOST #TODO: UPDATE
          value: localhost
        - name: ORDER_PORT
          value: '3004'
      - name: order-cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.0.0.preview.0  # make sure the use the latest version
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "64Mi"
            cpu: "10m"
        args:
          # If connecting from a VPC-native GKE cluster, you can use the
          # following flag to have the proxy connect over private IP
          - "--private-ip"
          # Enable structured logging with LogEntry format:
          - "--structured-logs"
          - "--port=5432"
          - "woven-fountain-359423:northamerica-northeast1:modular-db-instance"
        
        securityContext:
          runAsNonRoot: true

# ---
# apiVersion: autoscaling/v1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: order-app
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: order-app
#   minReplicas: 1
#   maxReplicas: 3
#   targetCPUUtilizationPercentage: 80

---
apiVersion: v1
kind: Service
metadata:
  name: order-svc
  # annotations:
  #   cloud.google.com/neg: '{"exposed_ports":{"3004":{}}}'
spec:
  ports:
  - port: 3004
    name: order-port-svc
    protocol: TCP
    targetPort: 3004
  selector:
    app: order-app
  type: ClusterIP